addons:
- dir: AstralKeys
  url: astral-keys
- dir: Auctionator
  url: auctionator
- dir: BigWigs
  url: big-wigs
- dir: BigWigs_Voice
  url: bigwigs_voice
- dir: LittleWigs
  url: little-wigs
- dir: Capping
  url: capping-bg-timers
- dir: CovenantMissionHelper
  url: covenantmissionhelper
- dir: Details
  url: details
- dir: Healers-Have-To-Die
  url: h-h-t-d
- dir: HandyNotes
  url: handynotes
- dir: MaxCam
  url: maxcam
- dir: Overachiever
  url: overachiever
- dir: PersonalLootHelper
  url: personal-loot-helper
- dir: Postal
  url: postal
- dir: Prat-3.0
  url: prat-3-0
- dir: RaiderIO
  url: raiderio
- dir: Rarity
  url: rarity
- dir: SharedMedia_Causese 
  url: haredmedia_causese
  url: simulationcraft
- dir: WeakAuras
  url: weakauras-2
- dir: WorldQuestTracker
  url: world-quest-tracker
- dir: Pawn
  url: pawn
- dir: ArkInventory
  url: ark-inventory
- dir: HandyNotes_DragonGlyphs
  url: handynotes-dragon-glyphs
- dir: BigWigs_Shadowlands
  url: bigwigs_shadowlands

addons_dir: /mnt/c/Program Files (x86)/World of Warcraft/_retail_/Interface/AddOns
