addons:
- dir: AskMrRobot
  url: askmrrobot
- dir: AstralKeys
  url: astral-keys
- dir: Auctionator
  url: auctionator
- dir: BigWigs
  url: big-wigs
- dir: LittleWigs
  url: little-wigs
- dir: Capping
  url: capping-bg-timers
- dir: CovenantMissionHelper
  url: covenantmissionhelper
- dir: CrossRealmAssist
  url: crossrealmassist
- dir: Details
  url: details
- dir: GarrisonMissionManager
  url: garrison-mission-manager
- dir: Gnosis
  url: gnosis
- dir: Healers-Have-To-Die
  url: h-h-t-d
- dir: HandyNotes
  url: handynotes
- dir: HandyNotes_DraenorTreasures
  url: handynotes_draenortreasures
- dir: HandyNotes_BattleForAzerothTreasures
  url: handynotes-battle-for-azeroth-treasures
- dir: HealBot
  url: heal-bot-continued
- dir: MaxCam
  url: maxcam
- dir: Mogit
  url: mogit
- dir: NPCScan
  url: npcscan
- dir: _NPCScan.Overlay
  url: npcscan-overlay
- dir: Overachiever
  url: overachiever
- dir: PersonalLootHelper
  url: personal-loot-helper
- dir: Postal
  url: postal
- dir: Prat-3.0
  url: prat-3-0
- dir: RaiderIO
  url: raiderio
- dir: Rarity
  url: rarity
- dir: Simulationcraft
  url: simulationcraft
- dir: Titan
  url: titan-panel
- dir: WeakAuras
  url: weakauras-2
- dir: WorldQuestTracker
  url: world-quest-tracker
- dir: XRoll
  url: xroll
- dir: ZPerl
  url: zperl
- dir: Pawn
  url: pawn
- dir: TrainingGrounds
  url: traininggrounds
- dir: ArkInventory
  url: ark-inventory
addons_dir: /Applications/World of Warcraft/_retail_/Interface/AddOns
